platform :ios, '6.0'
xcodeproj 'ShnergleApp.xcodeproj'
pod 'ECSlidingViewController', '~> 0.10.0'
pod 'Facebook-iOS-SDK', '~> 3.7.1'
pod 'Google-Maps-iOS-SDK', '~> 1.4.0'
pod 'GCPlaceholderTextView', '~> 1.0.1'
pod 'Toast', '~> 2.0'
pod 'UIImage-Resize', '~> 1.0'
pod 'TPKeyboardAvoiding', '~> 1.1'
pod 'NSDate+TimeAgo', '~> 1.0.2'
pod 'CorePlot', '~> 1.3'
pod 'NSDate-Escort', '~> 1.1.0'
