platform :ios, '5.1'
xcodeproj 'ShnergleApp.xcodeproj'
pod 'ECSlidingViewController', '~> 0.10.0'
pod 'Facebook-iOS-SDK', '~> 3.5.2'
pod 'Google-Maps-iOS-SDK', '~> 1.3.1'
pod 'SBJson', '~> 3.2.0'
pod 'GCPlaceholderTextView', '~> 1.0.1'
pod 'Toast', '~> 2.0'
pod 'UIImage-Resize', '~> 0.1'
pod 'TPKeyboardAvoiding', '~> 1.0'
